services:
  api:
    cpus: 0.15
    cpu_shares: 128
    healthcheck:
      interval: 120s
      timeout: 15s
  postgres:
    cpus: 0.10
    cpu_shares: 128
    healthcheck:
      interval: 120s
      timeout: 15s
  worker:
    cpus: 0.25
    cpu_shares: 128
    environment:
      OMP_NUM_THREADS: '1'
      OPENBLAS_NUM_THREADS: '1'
      MKL_NUM_THREADS: '1'
      NUMEXPR_NUM_THREADS: '1'
  research:
    cpus: 0.15
    cpu_shares: 128
  browser:
    cpus: 0.25
    cpu_shares: 128
